spring.config.import=optional:file:.env[.properties]

spring.application.name=portfolio-api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:portfolio}
spring.datasource.username=${POSTGRES_USER:portfolio}
spring.datasource.password=${POSTGRES_PASSWORD:portfolio}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.user.name=${API_USER:admin}
spring.security.user.password=${API_PASSWORD:admin}
